### ISSUE TITLE
Installation error (loguru)

### ISSUE THREAD

**Issue by rr4pr** [FicHub/fichub-cli#12]
Tried to install fichub-cli through pip, got error:  Could not find a version that satisfies the requirement loguru>=0.5.3
```
pip install -U fichub-cli
Collecting fichub-cli
  Downloading https://files.pythonhosted.org/packages/0a/36/8ba33a9ee2d639b66926422fa6c865908fd25345d53689318f864ad8f63d/fichub-cli-0.3.7.tar.gz
Collecting BeautifulSoup4>=4.9.3 (from fichub-cli)
  Using cached https://files.pythonhosted.org/packages/1c/d9/8c507915ff962b9e854b477b203c171074f59cce9465dac9f71c2b57ebd6/beautifulsoup4-4.9.3-py2-none-any.whl
Collecting click>=7.1.2 (from fichub-cli)
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
Collecting colorama>=0.4.4 (from fichub-cli)
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting loguru>=0.5.3 (from fichub-cli)
  Could not find a version that satisfies the requirement loguru>=0.5.3 (from fichub-cli) (from versions: )
No matching distribution found for loguru>=0.5.3 (from fichub-cli)
```

**Comment by arzkar** [comment]
1) Which versions of Python and Pip are you using?
2) Are you using a virtual environment like venv or pyenv or installing globally?
3) Which operating system are you using? WIndows or Linux or MacOS?

I tried reinstalling fichub-cli on my Python 3.8.5 pyenv environment and it worked fine.

**Comment by rr4pr** [comment]
>     1. Which versions of Python and Pip are you using?
> 
>     2. Are you using a virtual environment like venv or pyenv or installing globally?
> 
>     3. Which operating system are you using? WIndows or Linux or MacOS?

1. 2.7.17 & 9.0.1
2. globally
3. mint 19.3

**Comment by arzkar** [comment]
Python 2.7 huh? So thats the issue. The CLI only works with Python 3.
A possible solution is to use `pyenv` to manage multiple versions of Python and creating a virtualenv for fichub-cli with Python 3.7+. Thats how I manage my projects.'

Its better to use virtual environments instead of installing globally since some packages can conflict with others where different packages might need different versions of the same library.
