### ISSUE TITLE
opening the downloaded fic file after it's done

### ISSUE THREAD

**Issue by Arrow-x** [FicHub/fichub-cli#18]
either a `--exec` flag on the command or printing the destination folder to stdout

**Comment by arzkar** [comment]
You mean you want to be able to open the downloaded file in an ebook reader app once the download is complete? Thats outside the core purpose of the CLI and unfortunately, I neither have the time nor the will to add this feature.

**Comment by Arrow-x** [comment]
@arzkar I will try to work on this myself; since it should be simple enough.
Should I open a PR?

**Comment by arzkar** [comment]
Sure, you can work on it and open a PR.
